
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package memory.game;

import java.awt.Image;
import java.util.ArrayList;
import javax.swing.ImageIcon;

public class Flashcard extends javax.swing.JFrame {
    User currentUser;
    int index = 0;
    static boolean showTerm = true;
    String[][] CardArray;
    ArrayList<ArrayList<String>> StudyLaterArray;
    int x =0;
    int value;
    Sets currentSet;
    LoginUsers loginUsers;
    public Flashcard(Sets set,User  currentUser,LoginUsers loginUsers) {
        //constructor
        initComponents();    
        currentSet=set;
        this.currentUser = currentUser;
        this.loginUsers= loginUsers;
        CardArray = set.getCardArray();
        StudyLaterArray=set.getStudyArray();
        //sets text on card to first card term
        CardButton.setText(CardArray[index][0]);
        value = (index+1)*100/CardArray.length;
        ProgressField.setText("Progress " + (index + 1) + "/" + CardArray.length);        
        jProgressBar1.setValue(value);
        boolean starOn = currentSet.contain(CardArray[index][0], CardArray[index][1])!=-1;
        if(starOn){
            scaleStar();
        }else{
            scaleBlue();
        }
    }
    public void scaleStar(){
        ImageIcon icon = new ImageIcon("C:\\Users\\mcman\\OneDrive\\Documents\\GitHub\\Memory-Game\\build\\classes\\memory\\game\\StarImage\\Star.png");
        Image img = icon.getImage();
        Image imgScale = img.getScaledInstance(Star.getWidth(),Star.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imgScale);
        Star.setIcon(scaledIcon);
    }
    public void scaleBlue(){
        ImageIcon icon = new ImageIcon("C:\\Users\\mcman\\OneDrive\\Documents\\GitHub\\Memory-Game\\build\\classes\\memory\\game\\StarImage\\Blue.jpg");
        Image img = icon.getImage();
        Image imgScale = img.getScaledInstance(Star.getWidth(),Star.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imgScale);
        Star.setIcon(scaledIcon);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        progressBar = new javax.swing.JPanel();
        AddTermToStudyLaterButton = new javax.swing.JButton();
        ViewStudyLaterButton = new javax.swing.JButton();
        CardButton = new javax.swing.JButton();
        GoRightButton = new javax.swing.JButton();
        GoLeftButton = new javax.swing.JButton();
        ProgressField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        BackButton = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        Star = new javax.swing.JLabel();
        ProgressNumber = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        progressBar.setBackground(new java.awt.Color(0, 51, 102));

        AddTermToStudyLaterButton.setText("Add Term to Study Later");
        AddTermToStudyLaterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddTermToStudyLaterButtonActionPerformed(evt);
            }
        });

        ViewStudyLaterButton.setText("View Study Later");
        ViewStudyLaterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewStudyLaterButtonActionPerformed(evt);
            }
        });

        CardButton.setText("Term");
        CardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CardButtonActionPerformed(evt);
            }
        });

        GoRightButton.setText(">");
        GoRightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoRightButtonActionPerformed(evt);
            }
        });

        GoLeftButton.setText("<");
        GoLeftButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoLeftButtonActionPerformed(evt);
            }
        });

        ProgressField.setText("Progress");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Flashcards");

        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        jProgressBar1.setStringPainted(true);

        Star.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Star.setMaximumSize(new java.awt.Dimension(80, 80));
        Star.setMinimumSize(new java.awt.Dimension(40, 40));
        Star.setPreferredSize(new java.awt.Dimension(842, 800));

        ProgressNumber.setBackground(new java.awt.Color(0, 51, 102));
        ProgressNumber.setForeground(new java.awt.Color(0, 51, 102));
        ProgressNumber.setBorder(null);

        javax.swing.GroupLayout progressBarLayout = new javax.swing.GroupLayout(progressBar);
        progressBar.setLayout(progressBarLayout);
        progressBarLayout.setHorizontalGroup(
            progressBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(progressBarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(progressBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(progressBarLayout.createSequentialGroup()
                        .addGroup(progressBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(progressBarLayout.createSequentialGroup()
                                .addComponent(BackButton)
                                .addGap(79, 79, 79)
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(progressBarLayout.createSequentialGroup()
                                .addComponent(AddTermToStudyLaterButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ViewStudyLaterButton)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, progressBarLayout.createSequentialGroup()
                        .addGroup(progressBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(progressBarLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(Star, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(progressBarLayout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(progressBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(CardButton, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(progressBarLayout.createSequentialGroup()
                                        .addGroup(progressBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(GoLeftButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ProgressNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(progressBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, progressBarLayout.createSequentialGroup()
                                                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(29, 29, 29))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, progressBarLayout.createSequentialGroup()
                                                .addComponent(ProgressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(61, 61, 61)))
                                        .addComponent(GoRightButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(32, 32, 32))))
        );
        progressBarLayout.setVerticalGroup(
            progressBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, progressBarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(progressBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(progressBarLayout.createSequentialGroup()
                        .addGroup(progressBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BackButton)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, progressBarLayout.createSequentialGroup()
                        .addComponent(Star, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)))
                .addComponent(CardButton, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(progressBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(progressBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(GoLeftButton)
                        .addComponent(GoRightButton))
                    .addGroup(progressBarLayout.createSequentialGroup()
                        .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(progressBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(progressBarLayout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(ProgressNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(progressBarLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ProgressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGroup(progressBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ViewStudyLaterButton)
                    .addComponent(AddTermToStudyLaterButton))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(progressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        Home HomeScreen = new Home(currentUser,loginUsers);
        HomeScreen.setLocationRelativeTo(this);
        this.dispose();
        HomeScreen.setVisible(true);
    }//GEN-LAST:event_BackButtonActionPerformed

    private void GoLeftButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoLeftButtonActionPerformed
        if(index!=0){
            index--;
        }
        CardButton.setText(CardArray[index][0]);
        
        boolean starOn = currentSet.contain(CardArray[index][0], CardArray[index][1])!=-1;
        if(starOn){
            scaleStar();
        }else{
            scaleBlue();
        }   
        ProgressField.setText("Progress " + (index + 1) + "/" + CardArray.length);
        //progress bar
        value = (index+1)*100/CardArray.length;
        jProgressBar1.setValue(value);
    }//GEN-LAST:event_GoLeftButtonActionPerformed

    private void GoRightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoRightButtonActionPerformed
        if(index!=CardArray.length-1){
            index++;
        }
        CardButton.setText(CardArray[index][0]);
        boolean starOn = currentSet.contain(CardArray[index][0], CardArray[index][1])!=-1;
        if(starOn){
            scaleStar();
        }else{
            scaleBlue();
        }
        ProgressField.setText("Progress " + (index + 1) + "/" + CardArray.length);

        //progress bar
        value = (index+1)*100/CardArray.length;
        jProgressBar1.setValue(value);
    }//GEN-LAST:event_GoRightButtonActionPerformed

    private void CardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CardButtonActionPerformed
        if (showTerm == true) {
            CardButton.setText(CardArray[index][1]);
            showTerm = false;
        } else {
            CardButton.setText(CardArray[index][0]);
            showTerm = true;
        }
        ProgressField.setText("Progress " + (index + 1) + "/" + CardArray.length);
    }//GEN-LAST:event_CardButtonActionPerformed

    private void ViewStudyLaterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewStudyLaterButtonActionPerformed
        StudyLater studyLaterPage = new StudyLater(currentSet, currentUser,loginUsers);
        studyLaterPage.setLocationRelativeTo(this);
        this.dispose();
        studyLaterPage.setVisible(true);
    }//GEN-LAST:event_ViewStudyLaterButtonActionPerformed

    private void AddTermToStudyLaterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddTermToStudyLaterButtonActionPerformed
        if(currentSet.contain(CardArray[index][0], CardArray[index][1])==-1){
            StudyLaterArray.add(new ArrayList<String>());
            StudyLaterArray.get(x).add(0,CardArray[index][0]);
            StudyLaterArray.get(x).add(1,CardArray[index][1]);
            x++;
            scaleStar();
        }

    }//GEN-LAST:event_AddTermToStudyLaterButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddTermToStudyLaterButton;
    private javax.swing.JButton BackButton;
    private javax.swing.JButton CardButton;
    private javax.swing.JButton GoLeftButton;
    private javax.swing.JButton GoRightButton;
    private javax.swing.JTextField ProgressField;
    private javax.swing.JTextField ProgressNumber;
    private javax.swing.JLabel Star;
    private javax.swing.JButton ViewStudyLaterButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JPanel progressBar;
    // End of variables declaration//GEN-END:variables
}
